-- migrate:up

INSERT INTO songs (track_number, album_id, name, content, lyrics_by, music_by, is_title, lyrics, genre_id) 
VALUES
(3,1,"I See It Clearly","https://drive.google.com/uc?export=download&id=1FCEn9tvj56d-5zcdtQ-vUpP_eDu0kGKc","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,1),
(4,1,"The Old Willows Seem So Grey","https://drive.google.com/uc?export=download&id=1FcLGNKkTsoBi_-cW9aKFHB7tcjWpz0pl","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,1),
(5,1,"I love you","https://drive.google.com/uc?export=download&id=1UcgUIrWsZLOdekTUcmjO7idGNvQ7sZoe","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,1),
(2,2,"if you are not willing","https://drive.google.com/uc?export=download&id=170pIYZMqghB7e3D_Oiv5wBFDSxF8lSkx","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,1),
(3,2,"My father, my father","https://drive.google.com/uc?export=download&id=1CTA2fNbc45cfToVc1bFtT5e3_HGRYvVZ","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,1),
(2,3,"Has Done","https://drive.google.com/uc?export=download&id=17IOWyVZBUx-AYOAyTU3--9oPWklDdJ2z","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,2),
(3,3,"Rdes quickly","https://drive.google.com/uc?export=download&id=1h2_taxhu4fsYFI6E4tb_xcYAHuBOC-_6","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,2),
(2,4,"Groaning Child in His Arms","https://drive.google.com/uc?export=download&id=1LJBH4EMnxRYucx0kapbmUUHVm-1t4W7c","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,2),
(2,5,"Reaches the farm","https://drive.google.com/uc?export=download&id=1jfUerVNmIt5el7cgcR1K6ll_HJpGg5dH","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,2),
(3,6,"I play","https://drive.google.com/uc?export=download&id=1OOJR1GEnkbFxw_j4QDJtpOJJve6Qid-o","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,2),
(7,7,"colorful flowers","https://drive.google.com/uc?export=download&id=1Ih9_QOgLjeAYd7GhDh4UYgq4OgdAPJUd","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,3),
(3,8,"golden robe","https://drive.google.com/uc?export=download&id=1v47Xdvb3ScVXapb99ovyCMNxAXCVUmwy","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,3),
(2,9,"don't you hear","https://drive.google.com/uc?export=download&id=1QPIjfm4Da-7SR8l6JgSQIHCB7RXSKfWl","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,3),
(3,9,"promises","https://drive.google.com/uc?export=download&id=1DbwssbJFf0EgVb9YNT0zopadLrLbUwBA","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,3),
(2,10,"Be quiet, stay calm","https://drive.google.com/uc?export=download&id=1tjR1nB59FCMVyLgGLlFm3_CDnB3N2brR","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,3),
(4,9,"The wind whispers in dry leaves","https://drive.google.com/uc?export=download&id=1To6STZ23LSuNNnR3qGKws0FB_HhOQu-g","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,4),
(2,11,"Fine boy","https://drive.google.com/uc?export=download&id=1oH6P-yw8IitYxaHJGhS7tj-LlEeek_nV","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,4),
(3,11,"My daughters","https://drive.google.com/uc?export=download&id=1yU3IlwJiwEcKjNN4FmbipFoxqJczt7ai","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,4),
(6,12,"lead the nightly rhyme","https://drive.google.com/uc?export=download&id=19g2lE0HLdYEJ6nL3e3K8kFh_LpgzvWkQ","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,4),
(7,12,"rock and dance","https://drive.google.com/uc?export=download&id=1UD5CJSjE6x36l5MtkID8YvamuE44084r","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,4),
(4,13,"sing you in","https://drive.google.com/uc?export=download&id=1G0fjjxnXIqCNgIEF8WJOMKvftllH8p5O","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,5),
(5,13,"Don't you see there","https://drive.google.com/uc?export=download&id=1XUahM1ydBTo-RHbAOl5TdBzD0LEvI4ur","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,5),
(6,13,"My son","https://drive.google.com/uc?export=download&id=1l22xUWgs7vDQQM5kwrJo0m6p78EqECea","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,5),
(2,14,"The old willows","https://drive.google.com/uc?export=download&id=1P15NjDtjG3RRrnkSvsVAZ3y25R00HfaR","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,5),
(3,5,"Beautiful figure","https://drive.google.com/uc?export=download&id=1ypyzU9J5SqDqY_PLOWNRNqh6iYJlR-Gl","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,5),
(3,14,"Use force","https://drive.google.com/uc?export=download&id=1yG8RtyHgNrBKsGvopxF7dyjC0fxHSeX5","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,6),
(6,1,"Touching me","https://drive.google.com/uc?export=download&id=1tPFGfXfRty_HIHqki1Dj3v1F0UXKn0b_","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,6),
(3,15,"A Pity","https://drive.google.com/uc?export=download&id=1efwiucMB7WaKPP1Ydzl7lD2cYQYrl0b4","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,6),
(4,15,"Horrified","https://drive.google.com/uc?export=download&id=1JXNxFTlpYi7q31kn1o5lg6kSgRzB3luZ","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,6),
(8,7,"Holds","https://drive.google.com/uc?export=download&id=1rt3uxmssUi8GzZEHaiq_hc_GfC-EoULs","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,6),
(1,1,"With difficulty","https://drive.google.com/uc?export=download&id=1iInBGuTr2eviV3Pomp5bJ8ZS6mSqAfPx","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,7),
(2,1,"When I’m With You (Inst.)","https://drive.google.com/uc?export=download&id=1eA06Eb8bS9fL2zveO5XvFYfJtdSZRTMY","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,7),
(1,2,"Home","https://drive.google.com/uc?export=download&id=1Tv2G8XGy976JIOs9QRrifjEM4INrjOqR","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,7),
(1,3,"Follow Me","https://drive.google.com/uc?export=download&id=1KEGdSVvvI4PmaeTcja3_UgL0wviIaw-g","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,7),
(1,4,"Talk That Way","https://drive.google.com/uc?export=download&id=1mAj7MiEGg_SiLPpOQCZHA6oi88XDjv1c","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,7),
(1,5,"Pixie Dust","https://drive.google.com/uc?export=download&id=1PiKF6SeHTdVEuVgrWUtSnHv54bYzFt6_","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,8),
(1,6,"Pretty woman","https://drive.google.com/uc?export=download&id=1H9KJ-LGJCgHFTUSqo5YsLrCQiRDb_g_T","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,8),
(2,6,"Like This","https://drive.google.com/uc?export=download&id=1SxQve3sNoc8ZLv7jb-cLQI4JYA4hbisY","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,8),
(1,7,"Lucky Charm","https://drive.google.com/uc?export=download&id=1-E6kGEnfAb0tngR-GukcTMJtoBRrlHO-","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,8),
(2,7,"Lucky Charm (Inst.)","https://drive.google.com/uc?export=download&id=1AlVAo-i1gy-Midl20Wh1nnx8ta-WNFAZ","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,8),
(1,8,"Capsized","https://drive.google.com/uc?export=download&id=1JctiulD8jdjCvpaH-FGhRH-SoVHj8iZ_","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,9),
(2,8,"Capsized (Inst.)","https://drive.google.com/uc?export=download&id=1QMhn3OFPt7ySzM8lxxduAREhV52Op9yg","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,9),
(1,9,"Take Our Time","https://drive.google.com/uc?export=download&id=1yV7CedeQGvMPIyDx8Tug23s9FlNNy4R5","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,9),
(1,10,"Promise","https://drive.google.com/uc?export=download&id=1TCawcOzQ_mzwOJTOHY7JCor0jBNFI_ll","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,9),
(1,11,"Stay","https://drive.google.com/uc?export=download&id=1AqcGBN1UXC1GT9o0S9xKFoUIw-L3RAdI","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,9),
(1,12,"Runaway","https://drive.google.com/uc?export=download&id=1B221VWwvIKOXlyJbJk82StB8p1md_Kso","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,10),
(2,12,"Touchdown","https://drive.google.com/uc?export=download&id=1IfT__Yvhob7DEYz20-5q5084OTlHOd-F","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,10),
(3,12,"Alive (feat. Neoni)","https://drive.google.com/uc?export=download&id=1mx29RNCsIyekDFxoZ8j3yI3uKSxwRvvk","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,10),
(4,12,"Castle (feat. Leila Pari)","https://drive.google.com/uc?export=download&id=1pi9nr43YzqlzWn99MuF3vwYD5MGLSZLF","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,10),
(5,12,"Power (feat. braev)","https://drive.google.com/uc?export=download&id=1hgxi-bFz_m5GD9Y0Wm6IpRGHPqCGv-y8","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,10),
(3,7,"Way To You","https://drive.google.com/uc?export=download&id=1FWWLoCAZ30p36k3WWOx37QGj-ur_4otI","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,11),
(4,7,"Way To You (Inst.)","https://drive.google.com/uc?export=download&id=1QjR1aghzhLeGNWwkjQUkDWnnQiSflbHW","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,11),
(5,7,"Time","https://drive.google.com/uc?export=download&id=1KJZPW0-fO8KUUxZbDSdVNFa21bUtGdWN","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,11),
(6,7,"Time (Inst.)","https://drive.google.com/uc?export=download&id=1ZpO7nu97vaSaxpaxPn7pPe5gIlbbnyZm","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,11),
(1,13,"Shimmer","https://drive.google.com/uc?export=download&id=1avAsFdmIEDpnZ72fwhA9NWQ1O-kOeGkp","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,11),
(2,13,"Outside","https://drive.google.com/uc?export=download&id=17CGHfzsS5dgresSoZ2pn7_ZrMIP7pFjU","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,12),
(3,13,"Inferior","https://drive.google.com/uc?export=download&id=1sgdweKRF56M7bOH4HLtN7pGd7dt3DgZC","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,12),
(1,14,"Fly Again","https://drive.google.com/uc?export=download&id=1UVpO4Q3vqRgvcJSEjcIAgaiiSypmdN2h","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,12),
(1,15,"Father","https://drive.google.com/uc?export=download&id=10TucwIMB1gDbvUGQG_rv4OUFdpE09OAu","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,12),
(2,15,"Father (Inst.)","https://drive.google.com/uc?export=download&id=1W2y8BQ7Jz0Xry7nHXAV4JrncxeZIMtC4","공유마당 자유이용 저작물","공유마당 자유이용 저작물",0,null,12),
(1,16,"Shivers","https://drive.google.com/uc?export=download&id=1Fpguh4ObZbasE6AaToewq2-nrR68GVjk","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,12),
(1,17,"Phoenix","https://drive.google.com/uc?export=download&id=1HfrMfS9rJ6JGO-MgvDdS5bwJuzwqG-Sh","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,12),
(1,18,"23","https://drive.google.com/uc?export=download&id=1ePmb5kJJ6dwMcEGnrJoKLz4ZTPVkz0Sy","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,12),
(1,19,"Gravity","https://drive.google.com/uc?export=download&id=1wMxgYHM35Tt6rq6iqpYdtDOPFRZwMkF5","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,12),
(1,20,"Everything","https://drive.google.com/uc?export=download&id=1HtKZWG0YKJME_XMbFLobUNaSRkdN2BAy","공유마당 자유이용 저작물","공유마당 자유이용 저작물",1,null,12)

-- migrate:down

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE songs;
SET FOREIGN_KEY_CHECKS = 1;
